apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: news-system-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-system
      name: news-system
    spec:
      containers:
        - name: news-system-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
              name: configmap-system
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mount: /tmp
      volumes:
        - name: images
          persistenceVolumeClaim:
            claimName: images-persistence-volume-claim
        - name: session
          persistenceVolumeClaim:
            claimName: session-persistence-volume-claim
  selector:
    matchLabels:
      app: news-system
  serviceName: news-system-service