apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-database-deployment
spec:
  template:
    metadata:
      name: news-database
      labels:
        app: news-database
    spec:
      containers:
        - name: news-database-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: configmap-database
  replicas: 1
  selector:
    matchLabels:
      app: news-database