apiVersion: v1
kind: Pod
metadata:
    name: news-database
    labels:
        name: news-database
spec:
  containers:
    - name: news-database-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: configmap-database