apiVersion: v1
kind: Pod
metadata:
  name: storage-class-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-container
          name: second-pv
  volumes:
    name: second-pv
    persistentVolumeClaim: 
      claimName: persistent-volume-claim-2
