apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd # Específico do Google Platform
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none